apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: faas
  name: faas-gateway
  labels:
    app: faas-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: faas-gateway
  template:
    metadata:
      labels:
        app: faas-gateway
    spec:
      serviceAccountName: faas-gateway-sa
      containers:
      - name: faas-gateway
        # only use local image
        image: localhost/faas-gateway-app:latest
        imagePullPolicy: Never
        ports:
        - name: http
          containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        readinessProbe:
          tcpSocket:
            port: http
          initialDelaySeconds: 2
          periodSeconds: 5
        livenessProbe:
          tcpSocket:
            port: http
          initialDelaySeconds: 5
          periodSeconds: 10
