apiVersion: v1
kind: ServiceAccount
metadata:
  name: faas-gateway-sa
  namespace: faas

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: faas-gateway-role
  namespace: faas
rules:
- apiGroups: [""]
  resources: ["configmaps", "services"]
  verbs: ["create", "get", "list", "delete"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["create", "get", "list", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: faas-gateway-rolebinding
  namespace: faas
subjects:
- kind: ServiceAccount
  name: faas-gateway-sa
  namespace: faas
roleRef:
  kind: Role
  name: faas-gateway-role
  apiGroup: rbac.authorization.k8s.io