apiVersion: v1
kind: Service
metadata:
  namespace: faas
  name: faas-gateway
  labels:
    app: faas-gateway
spec:
  type: LoadBalancer
  selector:
    app: faas-gateway
  ports:
  - name: http
    port: 80
    targetPort: http